# Site settings
title: Sample Documentation
description: Documentation samples created by me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: just-the-docs

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Search settings
plugins:
  - jekyll-remote-theme
  - jekyll-jtd-search
remote_theme: pmarsceill/just-the-docs # Remote theme for Just the Docs

# Table of Contents (TOC) settings
plugins:
  - jekyll-jtd-toc

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
